name: IBNP
version: "0.12"
license: "GPL-2.0-or-later"
date: 2024-10-17
description: |
    Involutive Bases for Noncommutative Polynomials

authors:
    - name: Gareth A. Evans
      url: mailto:gareth@mathemateg.com
    - name: Christopher D. Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Christopher D. Wensley
      url: https://github.com/cdwensley

GAP: ">= 4.13.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "GBNP"
      version: ">= 1.1.0"
      url: "https://gap-packages.github.io/gbnp/"
    - name: "utils"
      version: ">= 0.81"
      url: "https://gap-packages.github.io/utils"

www: https://gap-packages.github.io/ibnp/
readme: README.md
packageinfo: https://gap-packages.github.io/ibnp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ibnp/releases/download/v0.12/IBNP-0.12.tar.gz

abstract: |
    The IBNP package provides methods for computing an involutive (Groebner) basis B for an ideal J over a polynomial ring R in both the commutative and noncommutative cases. Secondly, methods are provided to involutively reduce a given polynomial to its normal form in R/J.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    involutive bases.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>EW24</span>]   <b class='BibAuthor'>Evans, G. A. and Wensley, C. D.</b>,
     <i class='BibTitle'>IBNP, Involutive Bases for Noncommutative Polynomials,
             Version 0.12</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/ibnp/">https://gap-packages.github.io/ibnp/</a></span>.
    </p>
    

bibtex: |
    @misc{ IBNP,
      author =           {Evans, G. A. and Wensley, C. D.},
      title =            {{IBNP},    Involutive    Bases    for   Noncommutative
                          Polynomials, {V}ersion 0.12},
      month =            {Oct},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/ibnp/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{ibnp/}}},
      keywords =         {involutive bases},
      printedkey =       {EW24}
    }

